package com.yusen.umbrella;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderHeader implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("INTERFACE_RECORD_ID")
private java.lang.String INTERFACE_RECORD_ID;

@org.kie.api.definition.type.Label("INTERFACE_ACTION_CODE")
private java.lang.String INTERFACE_ACTION_CODE;

@org.kie.api.definition.type.Label("INTERFACE_CONDITION")
private java.lang.String INTERFACE_CONDITION;

@org.kie.api.definition.type.Label("INTERFACE_ERROR")
private java.lang.String INTERFACE_ERROR;

@org.kie.api.definition.type.Label("ACCESSORIAL_CHARGE")
private java.lang.String ACCESSORIAL_CHARGE;

@org.kie.api.definition.type.Label("ACTUAL_DELIVERY_DATE_TIME")
private java.lang.String ACTUAL_DELIVERY_DATE_TIME;

@org.kie.api.definition.type.Label("ACTUAL_SHIP_DATE_TIME")
private java.lang.String ACTUAL_SHIP_DATE_TIME;

@org.kie.api.definition.type.Label("BASE_FREIGHT_CHARGE")
private java.lang.String BASE_FREIGHT_CHARGE;

@org.kie.api.definition.type.Label("BOL_NUM_ALPHA")
private java.lang.String BOL_NUM_ALPHA;

@org.kie.api.definition.type.Label("CARRIER")
private java.lang.String CARRIER;

@org.kie.api.definition.type.Label("CARRIER_SERVICE")
private java.lang.String CARRIER_SERVICE;

@org.kie.api.definition.type.Label("CARRIER_GROUP")
private java.lang.String CARRIER_GROUP;

@org.kie.api.definition.type.Label("CARRIER_TYPE")
private java.lang.String CARRIER_TYPE;

@org.kie.api.definition.type.Label("COMPANY")
private java.lang.String COMPANY;

@org.kie.api.definition.type.Label("CONSOLIDATED")
private java.lang.String CONSOLIDATED;

@org.kie.api.definition.type.Label("CONSOLIDATION_ALLOWED")
private java.lang.String CONSOLIDATION_ALLOWED;

@org.kie.api.definition.type.Label("CONTAINERS_SHIPPED")
private java.lang.String CONTAINERS_SHIPPED;

@org.kie.api.definition.type.Label("CUSTOMER")
private java.lang.String CUSTOMER;

@org.kie.api.definition.type.Label("CUSTOMER_ADDRESS1")
private java.lang.String CUSTOMER_ADDRESS1;

@org.kie.api.definition.type.Label("CUSTOMER_ADDRESS2")
private java.lang.String CUSTOMER_ADDRESS2;

@org.kie.api.definition.type.Label("CUSTOMER_ADDRESS3")
private java.lang.String CUSTOMER_ADDRESS3;

@org.kie.api.definition.type.Label("CUSTOMER_ATTENTION_TO")
private java.lang.String CUSTOMER_ATTENTION_TO;

@org.kie.api.definition.type.Label("CUSTOMER_CITY")
private java.lang.String CUSTOMER_CITY;

@org.kie.api.definition.type.Label("CUSTOMER_COUNTRY")
private java.lang.String CUSTOMER_COUNTRY;

@org.kie.api.definition.type.Label("CUSTOMER_EMAIL_ADDRESS")
private java.lang.String CUSTOMER_EMAIL_ADDRESS;

@org.kie.api.definition.type.Label("CUSTOMER_FAX_NUM")
private java.lang.String CUSTOMER_FAX_NUM;

@org.kie.api.definition.type.Label("CUSTOMER_NAME")
private java.lang.String CUSTOMER_NAME;

@org.kie.api.definition.type.Label("CUSTOMER_PHONE_NUM")
private java.lang.String CUSTOMER_PHONE_NUM;

@org.kie.api.definition.type.Label("CUSTOMER_PO")
private java.lang.String CUSTOMER_PO;

@org.kie.api.definition.type.Label("CUSTOMER_POSTAL_CODE")
private java.lang.String CUSTOMER_POSTAL_CODE;

@org.kie.api.definition.type.Label("CUSTOMER_STATE")
private java.lang.String CUSTOMER_STATE;

@org.kie.api.definition.type.Label("ERP_ORDER")
private java.lang.String ERP_ORDER;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO")
private java.lang.String FREIGHT_BILL_TO;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_ADDRESS1")
private java.lang.String FREIGHT_BILL_TO_ADDRESS1;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_ADDRESS2")
private java.lang.String FREIGHT_BILL_TO_ADDRESS2;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_ADDRESS3")
private java.lang.String FREIGHT_BILL_TO_ADDRESS3;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_ATTENTION_TO")
private java.lang.String FREIGHT_BILL_TO_ATTENTION_TO;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_CITY")
private java.lang.String FREIGHT_BILL_TO_CITY;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_COUNTRY")
private java.lang.String FREIGHT_BILL_TO_COUNTRY;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_EMAIL_ADDRESS")
private java.lang.String FREIGHT_BILL_TO_EMAIL_ADDRESS;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_FAX_NUM")
private java.lang.String FREIGHT_BILL_TO_FAX_NUM;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_NAME")
private java.lang.String FREIGHT_BILL_TO_NAME;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_PHONE_NUM")
private java.lang.String FREIGHT_BILL_TO_PHONE_NUM;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_POSTAL_CODE")
private java.lang.String FREIGHT_BILL_TO_POSTAL_CODE;

@org.kie.api.definition.type.Label("FREIGHT_BILL_TO_STATE")
private java.lang.String FREIGHT_BILL_TO_STATE;

@org.kie.api.definition.type.Label("FREIGHT_DISCOUNT")
private java.lang.String FREIGHT_DISCOUNT;

@org.kie.api.definition.type.Label("FREIGHT_TERMS")
private java.lang.String FREIGHT_TERMS;

@org.kie.api.definition.type.Label("INTERMEDIATE_ADDRESS1")
private java.lang.String INTERMEDIATE_ADDRESS1;

@org.kie.api.definition.type.Label("INTERMEDIATE_ADDRESS2")
private java.lang.String INTERMEDIATE_ADDRESS2;

@org.kie.api.definition.type.Label("INTERMEDIATE_ADDRESS3")
private java.lang.String INTERMEDIATE_ADDRESS3;

@org.kie.api.definition.type.Label("INTERMEDIATE_ATTENTION_TO")
private java.lang.String INTERMEDIATE_ATTENTION_TO;

@org.kie.api.definition.type.Label("INTERMEDIATE_CITY")
private java.lang.String INTERMEDIATE_CITY;

@org.kie.api.definition.type.Label("INTERMEDIATE_CONSIGNEE")
private java.lang.String INTERMEDIATE_CONSIGNEE;

@org.kie.api.definition.type.Label("INTERMEDIATE_COUNTRY")
private java.lang.String INTERMEDIATE_COUNTRY;

@org.kie.api.definition.type.Label("INTERMEDIATE_EMAIL_ADDRESS")
private java.lang.String INTERMEDIATE_EMAIL_ADDRESS;

@org.kie.api.definition.type.Label("INTERMEDIATE_FAX_NUM")
private java.lang.String INTERMEDIATE_FAX_NUM;

@org.kie.api.definition.type.Label("INTERMEDIATE_NAME")
private java.lang.String INTERMEDIATE_NAME;

@org.kie.api.definition.type.Label("INTERMEDIATE_PHONE_NUM")
private java.lang.String INTERMEDIATE_PHONE_NUM;

@org.kie.api.definition.type.Label("INTERMEDIATE_POSTAL_CODE")
private java.lang.String INTERMEDIATE_POSTAL_CODE;

@org.kie.api.definition.type.Label("INTERMEDIATE_STATE")
private java.lang.String INTERMEDIATE_STATE;

@org.kie.api.definition.type.Label("LIABILITY_TERMS")
private java.lang.String LIABILITY_TERMS;

@org.kie.api.definition.type.Label("ORDER_DATE")
private java.lang.String ORDER_DATE;

@org.kie.api.definition.type.Label("ORDER_TYPE")
private java.lang.String ORDER_TYPE;

@org.kie.api.definition.type.Label("PLANNED_DELIVERY_DATE_TIME")
private java.lang.String PLANNED_DELIVERY_DATE_TIME;

@org.kie.api.definition.type.Label("PLANNED_SHIP_DATE")
private java.lang.String PLANNED_SHIP_DATE;

@org.kie.api.definition.type.Label("PRIORITY")
private java.lang.String PRIORITY;

@org.kie.api.definition.type.Label("PRO_NUM_ALPHA")
private java.lang.String PRO_NUM_ALPHA;

@org.kie.api.definition.type.Label("QUANTITY_UM")
private java.lang.String QUANTITY_UM;

@org.kie.api.definition.type.Label("REQUESTED_DELIVERY_DATE")
private java.lang.String REQUESTED_DELIVERY_DATE;

@org.kie.api.definition.type.Label("REQUESTED_DELIVERY_TYPE")
private java.lang.String REQUESTED_DELIVERY_TYPE;

@org.kie.api.definition.type.Label("ROUTE")
private java.lang.String ROUTE;

@org.kie.api.definition.type.Label("ROUTING_CODE")
private java.lang.String ROUTING_CODE;

@org.kie.api.definition.type.Label("SCHEDULED_SHIP_DATE")
private java.lang.String SCHEDULED_SHIP_DATE;

@org.kie.api.definition.type.Label("SHIPMENT_ID")
private java.lang.String SHIPMENT_ID;

@org.kie.api.definition.type.Label("SHIP_TO_PHONE_NUM")
private java.lang.String SHIP_TO_PHONE_NUM;

@org.kie.api.definition.type.Label("SHIP_TO")
private java.lang.String SHIP_TO;

@org.kie.api.definition.type.Label("SHIP_TO_ADDRESS1")
private java.lang.String SHIP_TO_ADDRESS1;

@org.kie.api.definition.type.Label("SHIP_TO_ADDRESS2")
private java.lang.String SHIP_TO_ADDRESS2;

@org.kie.api.definition.type.Label("SHIP_TO_ADDRESS3")
private java.lang.String SHIP_TO_ADDRESS3;

@org.kie.api.definition.type.Label("SHIP_TO_ATTENTION_TO")
private java.lang.String SHIP_TO_ATTENTION_TO;

@org.kie.api.definition.type.Label("SHIP_TO_CITY")
private java.lang.String SHIP_TO_CITY;

@org.kie.api.definition.type.Label("SHIP_TO_COUNTRY")
private java.lang.String SHIP_TO_COUNTRY;

@org.kie.api.definition.type.Label("SHIP_TO_EMAIL_ADDRESS")
private java.lang.String SHIP_TO_EMAIL_ADDRESS;

@org.kie.api.definition.type.Label("SHIP_TO_FAX_NUM")
private java.lang.String SHIP_TO_FAX_NUM;

@org.kie.api.definition.type.Label("SHIP_TO_NAME")
private java.lang.String SHIP_TO_NAME;

@org.kie.api.definition.type.Label("SHIP_TO_POSTAL_CODE")
private java.lang.String SHIP_TO_POSTAL_CODE;

@org.kie.api.definition.type.Label("SHIP_TO_STATE")
private java.lang.String SHIP_TO_STATE;

@org.kie.api.definition.type.Label("SINGLE_ITEM_CARTONS")
private java.lang.String SINGLE_ITEM_CARTONS;

@org.kie.api.definition.type.Label("STOP")
private java.lang.String STOP;

@org.kie.api.definition.type.Label("VALUE_SHIPPED")
private java.lang.String VALUE_SHIPPED;

@org.kie.api.definition.type.Label("VOLUME_SHIPPED")
private java.lang.String VOLUME_SHIPPED;

@org.kie.api.definition.type.Label("VOLUME_UM")
private java.lang.String VOLUME_UM;

@org.kie.api.definition.type.Label("WAREHOUSE")
private java.lang.String WAREHOUSE;

@org.kie.api.definition.type.Label("WEIGHT_SHIPPED")
private java.lang.String WEIGHT_SHIPPED;

@org.kie.api.definition.type.Label("WEIGHT_UM")
private java.lang.String WEIGHT_UM;

@org.kie.api.definition.type.Label("USER_DEF1")
private java.lang.String USER_DEF1;

@org.kie.api.definition.type.Label("USER_DEF2")
private java.lang.String USER_DEF2;

@org.kie.api.definition.type.Label("USER_DEF3")
private java.lang.String USER_DEF3;

@org.kie.api.definition.type.Label("USER_DEF4")
private java.lang.String USER_DEF4;

@org.kie.api.definition.type.Label("USER_DEF5")
private java.lang.String USER_DEF5;

@org.kie.api.definition.type.Label("USER_DEF6")
private java.lang.String USER_DEF6;

@org.kie.api.definition.type.Label("USER_DEF7")
private java.lang.String USER_DEF7;

@org.kie.api.definition.type.Label("USER_DEF8")
private java.lang.String USER_DEF8;

@org.kie.api.definition.type.Label("USER_STAMP")
private java.lang.String USER_STAMP;

@org.kie.api.definition.type.Label("PROCESS_STAMP")
private java.lang.String PROCESS_STAMP;

@org.kie.api.definition.type.Label("DATE_TIME_STAMP")
private java.lang.String DATE_TIME_STAMP;

@org.kie.api.definition.type.Label("TMP_INTERNAL_ORDER_NUM")
private java.lang.String TMP_INTERNAL_ORDER_NUM;

@org.kie.api.definition.type.Label("TMP_INTERNAL_SHIPMENT_NUM")
private java.lang.String TMP_INTERNAL_SHIPMENT_NUM;

@org.kie.api.definition.type.Label("EXPORT_TAX_ID")
private java.lang.String EXPORT_TAX_ID;

@org.kie.api.definition.type.Label("PARTIES")
private java.lang.String PARTIES;

@org.kie.api.definition.type.Label("LOADING_PIER")
private java.lang.String LOADING_PIER;

@org.kie.api.definition.type.Label("TRANSPORTATION_MODE")
private java.lang.String TRANSPORTATION_MODE;

@org.kie.api.definition.type.Label("EXPORT_PORT")
private java.lang.String EXPORT_PORT;

@org.kie.api.definition.type.Label("UNLOADING_PORT")
private java.lang.String UNLOADING_PORT;

@org.kie.api.definition.type.Label("FTZ")
private java.lang.String FTZ;

@org.kie.api.definition.type.Label("VALIDATED_LICENSE")
private java.lang.String VALIDATED_LICENSE;

@org.kie.api.definition.type.Label("LICENSE_EXP_DATE")
private java.lang.String LICENSE_EXP_DATE;

@org.kie.api.definition.type.Label("ECCN")
private java.lang.String ECCN;

@org.kie.api.definition.type.Label("AUTHORIZED_EMPL_NAME")
private java.lang.String AUTHORIZED_EMPL_NAME;

@org.kie.api.definition.type.Label("AUTHORIZED_EMPL_TITLE")
private java.lang.String AUTHORIZED_EMPL_TITLE;

@org.kie.api.definition.type.Label("CONTAINERIZED")
private java.lang.String CONTAINERIZED;

@org.kie.api.definition.type.Label("TOTAL_FREIGHT_CHARGE")
private java.lang.String TOTAL_FREIGHT_CHARGE;

@org.kie.api.definition.type.Label("CUSTOMER_RESIDENTIAL_FLAG")
private java.lang.String CUSTOMER_RESIDENTIAL_FLAG;

@org.kie.api.definition.type.Label("SHIPTO_RESIDENTIAL_FLAG")
private java.lang.String SHIPTO_RESIDENTIAL_FLAG;

@org.kie.api.definition.type.Label("REJECTION_NOTE")
private java.lang.String REJECTION_NOTE;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY1")
private java.lang.String CUSTOMER_CATEGORY1;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY2")
private java.lang.String CUSTOMER_CATEGORY2;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY3")
private java.lang.String CUSTOMER_CATEGORY3;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY4")
private java.lang.String CUSTOMER_CATEGORY4;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY5")
private java.lang.String CUSTOMER_CATEGORY5;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY6")
private java.lang.String CUSTOMER_CATEGORY6;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY7")
private java.lang.String CUSTOMER_CATEGORY7;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY8")
private java.lang.String CUSTOMER_CATEGORY8;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY9")
private java.lang.String CUSTOMER_CATEGORY9;

@org.kie.api.definition.type.Label("CUSTOMER_CATEGORY10")
private java.lang.String CUSTOMER_CATEGORY10;

@org.kie.api.definition.type.Label("PROCESS_TYPE")
private java.lang.String PROCESS_TYPE;

@org.kie.api.definition.type.Label("CREATION_PROCESS_STAMP")
private java.lang.String CREATION_PROCESS_STAMP;

@org.kie.api.definition.type.Label("CREATION_DATE_TIME_STAMP")
private java.lang.String CREATION_DATE_TIME_STAMP;

@org.kie.api.definition.type.Label("CONSOLIDATION_DOCK_LOC_AREA")
private java.lang.String CONSOLIDATION_DOCK_LOC_AREA;

@org.kie.api.definition.type.Label("CONSOLIDATION_DOCK_LOC_POS")
private java.lang.String CONSOLIDATION_DOCK_LOC_POS;

@org.kie.api.definition.type.Label("IMMEDIATE_NEEDS_NOTE")
private java.lang.String IMMEDIATE_NEEDS_NOTE;

@org.kie.api.definition.type.Label("ALLOCATE_COMPLETE")
private java.lang.String ALLOCATE_COMPLETE;

@org.kie.api.definition.type.Label("ALTERNATE_EMAIL_ADDRESS")
private java.lang.String ALTERNATE_EMAIL_ADDRESS;

@org.kie.api.definition.type.Label("STOP_SEQUENCE")
private java.lang.String STOP_SEQUENCE;

@org.kie.api.definition.type.Label("CREATE_ORDERS")
private java.lang.String CREATE_ORDERS;

@org.kie.api.definition.type.Label("STORE_DISTRIBUTION")
private java.lang.String STORE_DISTRIBUTION;

@org.kie.api.definition.type.Label("SHIPPER_CODE")
private java.lang.String SHIPPER_CODE;

@org.kie.api.definition.type.Label("USER_DEF9")
private java.lang.String USER_DEF9;

@org.kie.api.definition.type.Label("USER_DEF10")
private java.lang.String USER_DEF10;

@org.kie.api.definition.type.Label("USER_DEF11")
private java.lang.String USER_DEF11;

@org.kie.api.definition.type.Label("USER_DEF12")
private java.lang.String USER_DEF12;

@org.kie.api.definition.type.Label("USER_DEF13")
private java.lang.String USER_DEF13;

@org.kie.api.definition.type.Label("USER_DEF14")
private java.lang.String USER_DEF14;

@org.kie.api.definition.type.Label("USER_DEF15")
private java.lang.String USER_DEF15;

@org.kie.api.definition.type.Label("USER_DEF16")
private java.lang.String USER_DEF16;

@org.kie.api.definition.type.Label("USER_DEF17_DATE_TIME")
private java.lang.String USER_DEF17_DATE_TIME;

@org.kie.api.definition.type.Label("USER_DEF18_DATE_TIME")
private java.lang.String USER_DEF18_DATE_TIME;

@org.kie.api.definition.type.Label("USER_DEF19_DATE_TIME")
private java.lang.String USER_DEF19_DATE_TIME;

@org.kie.api.definition.type.Label("USER_DEF20_DATE_TIME")
private java.lang.String USER_DEF20_DATE_TIME;




	public OrderHeader() {
	}

	public java.lang.String getINTERFACE_RECORD_ID() {
return this.INTERFACE_RECORD_ID;
}

public java.lang.String getINTERFACE_ACTION_CODE() {
return this.INTERFACE_ACTION_CODE;
}

public java.lang.String getINTERFACE_CONDITION() {
return this.INTERFACE_CONDITION;
}

public java.lang.String getINTERFACE_ERROR() {
return this.INTERFACE_ERROR;
}

public java.lang.String getACCESSORIAL_CHARGE() {
return this.ACCESSORIAL_CHARGE;
}

public java.lang.String getACTUAL_DELIVERY_DATE_TIME() {
return this.ACTUAL_DELIVERY_DATE_TIME;
}

public java.lang.String getACTUAL_SHIP_DATE_TIME() {
return this.ACTUAL_SHIP_DATE_TIME;
}

public java.lang.String getBASE_FREIGHT_CHARGE() {
return this.BASE_FREIGHT_CHARGE;
}

public java.lang.String getBOL_NUM_ALPHA() {
return this.BOL_NUM_ALPHA;
}

public java.lang.String getCARRIER() {
return this.CARRIER;
}

public java.lang.String getCARRIER_SERVICE() {
return this.CARRIER_SERVICE;
}

public java.lang.String getCARRIER_GROUP() {
return this.CARRIER_GROUP;
}

public java.lang.String getCARRIER_TYPE() {
return this.CARRIER_TYPE;
}

public java.lang.String getCOMPANY() {
return this.COMPANY;
}

public java.lang.String getCONSOLIDATED() {
return this.CONSOLIDATED;
}

public java.lang.String getCONSOLIDATION_ALLOWED() {
return this.CONSOLIDATION_ALLOWED;
}

public java.lang.String getCONTAINERS_SHIPPED() {
return this.CONTAINERS_SHIPPED;
}

public java.lang.String getCUSTOMER() {
return this.CUSTOMER;
}

public java.lang.String getCUSTOMER_ADDRESS1() {
return this.CUSTOMER_ADDRESS1;
}

public java.lang.String getCUSTOMER_ADDRESS2() {
return this.CUSTOMER_ADDRESS2;
}

public java.lang.String getCUSTOMER_ADDRESS3() {
return this.CUSTOMER_ADDRESS3;
}

public java.lang.String getCUSTOMER_ATTENTION_TO() {
return this.CUSTOMER_ATTENTION_TO;
}

public java.lang.String getCUSTOMER_CITY() {
return this.CUSTOMER_CITY;
}

public java.lang.String getCUSTOMER_COUNTRY() {
return this.CUSTOMER_COUNTRY;
}

public java.lang.String getCUSTOMER_EMAIL_ADDRESS() {
return this.CUSTOMER_EMAIL_ADDRESS;
}

public java.lang.String getCUSTOMER_FAX_NUM() {
return this.CUSTOMER_FAX_NUM;
}

public java.lang.String getCUSTOMER_NAME() {
return this.CUSTOMER_NAME;
}

public java.lang.String getCUSTOMER_PHONE_NUM() {
return this.CUSTOMER_PHONE_NUM;
}

public java.lang.String getCUSTOMER_PO() {
return this.CUSTOMER_PO;
}

public java.lang.String getCUSTOMER_POSTAL_CODE() {
return this.CUSTOMER_POSTAL_CODE;
}

public java.lang.String getCUSTOMER_STATE() {
return this.CUSTOMER_STATE;
}

public java.lang.String getERP_ORDER() {
return this.ERP_ORDER;
}

public java.lang.String getFREIGHT_BILL_TO() {
return this.FREIGHT_BILL_TO;
}

public java.lang.String getFREIGHT_BILL_TO_ADDRESS1() {
return this.FREIGHT_BILL_TO_ADDRESS1;
}

public java.lang.String getFREIGHT_BILL_TO_ADDRESS2() {
return this.FREIGHT_BILL_TO_ADDRESS2;
}

public java.lang.String getFREIGHT_BILL_TO_ADDRESS3() {
return this.FREIGHT_BILL_TO_ADDRESS3;
}

public java.lang.String getFREIGHT_BILL_TO_ATTENTION_TO() {
return this.FREIGHT_BILL_TO_ATTENTION_TO;
}

public java.lang.String getFREIGHT_BILL_TO_CITY() {
return this.FREIGHT_BILL_TO_CITY;
}

public java.lang.String getFREIGHT_BILL_TO_COUNTRY() {
return this.FREIGHT_BILL_TO_COUNTRY;
}

public java.lang.String getFREIGHT_BILL_TO_EMAIL_ADDRESS() {
return this.FREIGHT_BILL_TO_EMAIL_ADDRESS;
}

public java.lang.String getFREIGHT_BILL_TO_FAX_NUM() {
return this.FREIGHT_BILL_TO_FAX_NUM;
}

public java.lang.String getFREIGHT_BILL_TO_NAME() {
return this.FREIGHT_BILL_TO_NAME;
}

public java.lang.String getFREIGHT_BILL_TO_PHONE_NUM() {
return this.FREIGHT_BILL_TO_PHONE_NUM;
}

public java.lang.String getFREIGHT_BILL_TO_POSTAL_CODE() {
return this.FREIGHT_BILL_TO_POSTAL_CODE;
}

public java.lang.String getFREIGHT_BILL_TO_STATE() {
return this.FREIGHT_BILL_TO_STATE;
}

public java.lang.String getFREIGHT_DISCOUNT() {
return this.FREIGHT_DISCOUNT;
}

public java.lang.String getFREIGHT_TERMS() {
return this.FREIGHT_TERMS;
}

public java.lang.String getINTERMEDIATE_ADDRESS1() {
return this.INTERMEDIATE_ADDRESS1;
}

public java.lang.String getINTERMEDIATE_ADDRESS2() {
return this.INTERMEDIATE_ADDRESS2;
}

public java.lang.String getINTERMEDIATE_ADDRESS3() {
return this.INTERMEDIATE_ADDRESS3;
}

public java.lang.String getINTERMEDIATE_ATTENTION_TO() {
return this.INTERMEDIATE_ATTENTION_TO;
}

public java.lang.String getINTERMEDIATE_CITY() {
return this.INTERMEDIATE_CITY;
}

public java.lang.String getINTERMEDIATE_CONSIGNEE() {
return this.INTERMEDIATE_CONSIGNEE;
}

public java.lang.String getINTERMEDIATE_COUNTRY() {
return this.INTERMEDIATE_COUNTRY;
}

public java.lang.String getINTERMEDIATE_EMAIL_ADDRESS() {
return this.INTERMEDIATE_EMAIL_ADDRESS;
}

public java.lang.String getINTERMEDIATE_FAX_NUM() {
return this.INTERMEDIATE_FAX_NUM;
}

public java.lang.String getINTERMEDIATE_NAME() {
return this.INTERMEDIATE_NAME;
}

public java.lang.String getINTERMEDIATE_PHONE_NUM() {
return this.INTERMEDIATE_PHONE_NUM;
}

public java.lang.String getINTERMEDIATE_POSTAL_CODE() {
return this.INTERMEDIATE_POSTAL_CODE;
}

public java.lang.String getINTERMEDIATE_STATE() {
return this.INTERMEDIATE_STATE;
}

public java.lang.String getLIABILITY_TERMS() {
return this.LIABILITY_TERMS;
}

public java.lang.String getORDER_DATE() {
return this.ORDER_DATE;
}

public java.lang.String getORDER_TYPE() {
return this.ORDER_TYPE;
}

public java.lang.String getPLANNED_DELIVERY_DATE_TIME() {
return this.PLANNED_DELIVERY_DATE_TIME;
}

public java.lang.String getPLANNED_SHIP_DATE() {
return this.PLANNED_SHIP_DATE;
}

public java.lang.String getPRIORITY() {
return this.PRIORITY;
}

public java.lang.String getPRO_NUM_ALPHA() {
return this.PRO_NUM_ALPHA;
}

public java.lang.String getQUANTITY_UM() {
return this.QUANTITY_UM;
}

public java.lang.String getREQUESTED_DELIVERY_DATE() {
return this.REQUESTED_DELIVERY_DATE;
}

public java.lang.String getREQUESTED_DELIVERY_TYPE() {
return this.REQUESTED_DELIVERY_TYPE;
}

public java.lang.String getROUTE() {
return this.ROUTE;
}

public java.lang.String getROUTING_CODE() {
return this.ROUTING_CODE;
}

public java.lang.String getSCHEDULED_SHIP_DATE() {
return this.SCHEDULED_SHIP_DATE;
}

public java.lang.String getSHIPMENT_ID() {
return this.SHIPMENT_ID;
}

public java.lang.String getSHIP_TO_PHONE_NUM() {
return this.SHIP_TO_PHONE_NUM;
}

public java.lang.String getSHIP_TO() {
return this.SHIP_TO;
}

public java.lang.String getSHIP_TO_ADDRESS1() {
return this.SHIP_TO_ADDRESS1;
}

public java.lang.String getSHIP_TO_ADDRESS2() {
return this.SHIP_TO_ADDRESS2;
}

public java.lang.String getSHIP_TO_ADDRESS3() {
return this.SHIP_TO_ADDRESS3;
}

public java.lang.String getSHIP_TO_ATTENTION_TO() {
return this.SHIP_TO_ATTENTION_TO;
}

public java.lang.String getSHIP_TO_CITY() {
return this.SHIP_TO_CITY;
}

public java.lang.String getSHIP_TO_COUNTRY() {
return this.SHIP_TO_COUNTRY;
}

public java.lang.String getSHIP_TO_EMAIL_ADDRESS() {
return this.SHIP_TO_EMAIL_ADDRESS;
}

public java.lang.String getSHIP_TO_FAX_NUM() {
return this.SHIP_TO_FAX_NUM;
}

public java.lang.String getSHIP_TO_NAME() {
return this.SHIP_TO_NAME;
}

public java.lang.String getSHIP_TO_POSTAL_CODE() {
return this.SHIP_TO_POSTAL_CODE;
}

public java.lang.String getSHIP_TO_STATE() {
return this.SHIP_TO_STATE;
}

public java.lang.String getSINGLE_ITEM_CARTONS() {
return this.SINGLE_ITEM_CARTONS;
}

public java.lang.String getSTOP() {
return this.STOP;
}

public java.lang.String getVALUE_SHIPPED() {
return this.VALUE_SHIPPED;
}

public java.lang.String getVOLUME_SHIPPED() {
return this.VOLUME_SHIPPED;
}

public java.lang.String getVOLUME_UM() {
return this.VOLUME_UM;
}

public java.lang.String getWAREHOUSE() {
return this.WAREHOUSE;
}

public java.lang.String getWEIGHT_SHIPPED() {
return this.WEIGHT_SHIPPED;
}

public java.lang.String getWEIGHT_UM() {
return this.WEIGHT_UM;
}

public java.lang.String getUSER_DEF1() {
return this.USER_DEF1;
}

public java.lang.String getUSER_DEF2() {
return this.USER_DEF2;
}

public java.lang.String getUSER_DEF3() {
return this.USER_DEF3;
}

public java.lang.String getUSER_DEF4() {
return this.USER_DEF4;
}

public java.lang.String getUSER_DEF5() {
return this.USER_DEF5;
}

public java.lang.String getUSER_DEF6() {
return this.USER_DEF6;
}

public java.lang.String getUSER_DEF7() {
return this.USER_DEF7;
}

public java.lang.String getUSER_DEF8() {
return this.USER_DEF8;
}

public java.lang.String getUSER_STAMP() {
return this.USER_STAMP;
}

public java.lang.String getPROCESS_STAMP() {
return this.PROCESS_STAMP;
}

public java.lang.String getDATE_TIME_STAMP() {
return this.DATE_TIME_STAMP;
}

public java.lang.String getTMP_INTERNAL_ORDER_NUM() {
return this.TMP_INTERNAL_ORDER_NUM;
}

public java.lang.String getTMP_INTERNAL_SHIPMENT_NUM() {
return this.TMP_INTERNAL_SHIPMENT_NUM;
}

public java.lang.String getEXPORT_TAX_ID() {
return this.EXPORT_TAX_ID;
}

public java.lang.String getPARTIES() {
return this.PARTIES;
}

public java.lang.String getLOADING_PIER() {
return this.LOADING_PIER;
}

public java.lang.String getTRANSPORTATION_MODE() {
return this.TRANSPORTATION_MODE;
}

public java.lang.String getEXPORT_PORT() {
return this.EXPORT_PORT;
}

public java.lang.String getUNLOADING_PORT() {
return this.UNLOADING_PORT;
}

public java.lang.String getFTZ() {
return this.FTZ;
}

public java.lang.String getVALIDATED_LICENSE() {
return this.VALIDATED_LICENSE;
}

public java.lang.String getLICENSE_EXP_DATE() {
return this.LICENSE_EXP_DATE;
}

public java.lang.String getECCN() {
return this.ECCN;
}

public java.lang.String getAUTHORIZED_EMPL_NAME() {
return this.AUTHORIZED_EMPL_NAME;
}

public java.lang.String getAUTHORIZED_EMPL_TITLE() {
return this.AUTHORIZED_EMPL_TITLE;
}

public java.lang.String getCONTAINERIZED() {
return this.CONTAINERIZED;
}

public java.lang.String getTOTAL_FREIGHT_CHARGE() {
return this.TOTAL_FREIGHT_CHARGE;
}

public java.lang.String getCUSTOMER_RESIDENTIAL_FLAG() {
return this.CUSTOMER_RESIDENTIAL_FLAG;
}

public java.lang.String getSHIPTO_RESIDENTIAL_FLAG() {
return this.SHIPTO_RESIDENTIAL_FLAG;
}

public java.lang.String getREJECTION_NOTE() {
return this.REJECTION_NOTE;
}

public java.lang.String getCUSTOMER_CATEGORY1() {
return this.CUSTOMER_CATEGORY1;
}

public java.lang.String getCUSTOMER_CATEGORY2() {
return this.CUSTOMER_CATEGORY2;
}

public java.lang.String getCUSTOMER_CATEGORY3() {
return this.CUSTOMER_CATEGORY3;
}

public java.lang.String getCUSTOMER_CATEGORY4() {
return this.CUSTOMER_CATEGORY4;
}

public java.lang.String getCUSTOMER_CATEGORY5() {
return this.CUSTOMER_CATEGORY5;
}

public java.lang.String getCUSTOMER_CATEGORY6() {
return this.CUSTOMER_CATEGORY6;
}

public java.lang.String getCUSTOMER_CATEGORY7() {
return this.CUSTOMER_CATEGORY7;
}

public java.lang.String getCUSTOMER_CATEGORY8() {
return this.CUSTOMER_CATEGORY8;
}

public java.lang.String getCUSTOMER_CATEGORY9() {
return this.CUSTOMER_CATEGORY9;
}

public java.lang.String getCUSTOMER_CATEGORY10() {
return this.CUSTOMER_CATEGORY10;
}

public java.lang.String getPROCESS_TYPE() {
return this.PROCESS_TYPE;
}

public java.lang.String getCREATION_PROCESS_STAMP() {
return this.CREATION_PROCESS_STAMP;
}

public java.lang.String getCREATION_DATE_TIME_STAMP() {
return this.CREATION_DATE_TIME_STAMP;
}

public java.lang.String getCONSOLIDATION_DOCK_LOC_AREA() {
return this.CONSOLIDATION_DOCK_LOC_AREA;
}

public java.lang.String getCONSOLIDATION_DOCK_LOC_POS() {
return this.CONSOLIDATION_DOCK_LOC_POS;
}

public java.lang.String getIMMEDIATE_NEEDS_NOTE() {
return this.IMMEDIATE_NEEDS_NOTE;
}

public java.lang.String getALLOCATE_COMPLETE() {
return this.ALLOCATE_COMPLETE;
}

public java.lang.String getALTERNATE_EMAIL_ADDRESS() {
return this.ALTERNATE_EMAIL_ADDRESS;
}

public java.lang.String getSTOP_SEQUENCE() {
return this.STOP_SEQUENCE;
}

public java.lang.String getCREATE_ORDERS() {
return this.CREATE_ORDERS;
}

public java.lang.String getSTORE_DISTRIBUTION() {
return this.STORE_DISTRIBUTION;
}

public java.lang.String getSHIPPER_CODE() {
return this.SHIPPER_CODE;
}

public java.lang.String getUSER_DEF9() {
return this.USER_DEF9;
}

public java.lang.String getUSER_DEF10() {
return this.USER_DEF10;
}

public java.lang.String getUSER_DEF11() {
return this.USER_DEF11;
}

public java.lang.String getUSER_DEF12() {
return this.USER_DEF12;
}

public java.lang.String getUSER_DEF13() {
return this.USER_DEF13;
}

public java.lang.String getUSER_DEF14() {
return this.USER_DEF14;
}

public java.lang.String getUSER_DEF15() {
return this.USER_DEF15;
}

public java.lang.String getUSER_DEF16() {
return this.USER_DEF16;
}

public java.lang.String getUSER_DEF17_DATE_TIME() {
return this.USER_DEF17_DATE_TIME;
}

public java.lang.String getUSER_DEF18_DATE_TIME() {
return this.USER_DEF18_DATE_TIME;
}

public java.lang.String getUSER_DEF19_DATE_TIME() {
return this.USER_DEF19_DATE_TIME;
}

public java.lang.String getUSER_DEF20_DATE_TIME() {
return this.USER_DEF20_DATE_TIME;
}


	public OrderHeader(
			java.lang.String vINTERFACE_RECORD_ID,
java.lang.String INTERFACE_ACTION_CODE,
java.lang.String INTERFACE_CONDITION,
java.lang.String INTERFACE_ERROR,
java.lang.String ACCESSORIAL_CHARGE,
java.lang.String ACTUAL_DELIVERY_DATE_TIME,
java.lang.String ACTUAL_SHIP_DATE_TIME,
java.lang.String BASE_FREIGHT_CHARGE,
java.lang.String BOL_NUM_ALPHA,
java.lang.String CARRIER,
java.lang.String CARRIER_SERVICE,
java.lang.String CARRIER_GROUP,
java.lang.String CARRIER_TYPE,
java.lang.String COMPANY,
java.lang.String CONSOLIDATED,
java.lang.String CONSOLIDATION_ALLOWED,
java.lang.String CONTAINERS_SHIPPED,
java.lang.String CUSTOMER,
java.lang.String CUSTOMER_ADDRESS1,
java.lang.String CUSTOMER_ADDRESS2,
java.lang.String CUSTOMER_ADDRESS3,
java.lang.String CUSTOMER_ATTENTION_TO,
java.lang.String CUSTOMER_CITY,
java.lang.String CUSTOMER_COUNTRY,
java.lang.String CUSTOMER_EMAIL_ADDRESS,
java.lang.String CUSTOMER_FAX_NUM,
java.lang.String CUSTOMER_NAME,
java.lang.String CUSTOMER_PHONE_NUM,
java.lang.String CUSTOMER_PO,
java.lang.String CUSTOMER_POSTAL_CODE,
java.lang.String CUSTOMER_STATE,
java.lang.String ERP_ORDER,
java.lang.String FREIGHT_BILL_TO,
java.lang.String FREIGHT_BILL_TO_ADDRESS1,
java.lang.String FREIGHT_BILL_TO_ADDRESS2,
java.lang.String FREIGHT_BILL_TO_ADDRESS3,
java.lang.String FREIGHT_BILL_TO_ATTENTION_TO,
java.lang.String FREIGHT_BILL_TO_CITY,
java.lang.String FREIGHT_BILL_TO_COUNTRY,
java.lang.String FREIGHT_BILL_TO_EMAIL_ADDRESS,
java.lang.String FREIGHT_BILL_TO_FAX_NUM,
java.lang.String FREIGHT_BILL_TO_NAME,
java.lang.String FREIGHT_BILL_TO_PHONE_NUM,
java.lang.String FREIGHT_BILL_TO_POSTAL_CODE,
java.lang.String FREIGHT_BILL_TO_STATE,
java.lang.String FREIGHT_DISCOUNT,
java.lang.String FREIGHT_TERMS,
java.lang.String INTERMEDIATE_ADDRESS1,
java.lang.String INTERMEDIATE_ADDRESS2,
java.lang.String INTERMEDIATE_ADDRESS3,
java.lang.String INTERMEDIATE_ATTENTION_TO,
java.lang.String INTERMEDIATE_CITY,
java.lang.String INTERMEDIATE_CONSIGNEE,
java.lang.String INTERMEDIATE_COUNTRY,
java.lang.String INTERMEDIATE_EMAIL_ADDRESS,
java.lang.String INTERMEDIATE_FAX_NUM,
java.lang.String INTERMEDIATE_NAME,
java.lang.String INTERMEDIATE_PHONE_NUM,
java.lang.String INTERMEDIATE_POSTAL_CODE,
java.lang.String INTERMEDIATE_STATE,
java.lang.String LIABILITY_TERMS,
java.lang.String ORDER_DATE,
java.lang.String ORDER_TYPE,
java.lang.String PLANNED_DELIVERY_DATE_TIME,
java.lang.String PLANNED_SHIP_DATE,
java.lang.String PRIORITY,
java.lang.String PRO_NUM_ALPHA,
java.lang.String QUANTITY_UM,
java.lang.String REQUESTED_DELIVERY_DATE,
java.lang.String REQUESTED_DELIVERY_TYPE,
java.lang.String ROUTE,
java.lang.String ROUTING_CODE,
java.lang.String SCHEDULED_SHIP_DATE,
java.lang.String SHIPMENT_ID,
java.lang.String SHIP_TO_PHONE_NUM,
java.lang.String SHIP_TO,
java.lang.String SHIP_TO_ADDRESS1,
java.lang.String SHIP_TO_ADDRESS2,
java.lang.String SHIP_TO_ADDRESS3,
java.lang.String SHIP_TO_ATTENTION_TO,
java.lang.String SHIP_TO_CITY,
java.lang.String SHIP_TO_COUNTRY,
java.lang.String SHIP_TO_EMAIL_ADDRESS,
java.lang.String SHIP_TO_FAX_NUM,
java.lang.String SHIP_TO_NAME,
java.lang.String SHIP_TO_POSTAL_CODE,
java.lang.String SHIP_TO_STATE,
java.lang.String SINGLE_ITEM_CARTONS,
java.lang.String STOP,
java.lang.String VALUE_SHIPPED,
java.lang.String VOLUME_SHIPPED,
java.lang.String VOLUME_UM,
java.lang.String WAREHOUSE,
java.lang.String WEIGHT_SHIPPED,
java.lang.String WEIGHT_UM,
java.lang.String USER_DEF1,
java.lang.String USER_DEF2,
java.lang.String USER_DEF3,
java.lang.String USER_DEF4,
java.lang.String USER_DEF5,
java.lang.String USER_DEF6,
java.lang.String USER_DEF7,
java.lang.String USER_DEF8,
java.lang.String USER_STAMP,
java.lang.String PROCESS_STAMP,
java.lang.String DATE_TIME_STAMP,
java.lang.String TMP_INTERNAL_ORDER_NUM,
java.lang.String TMP_INTERNAL_SHIPMENT_NUM,
java.lang.String EXPORT_TAX_ID,
java.lang.String PARTIES,
java.lang.String LOADING_PIER,
java.lang.String TRANSPORTATION_MODE,
java.lang.String EXPORT_PORT,
java.lang.String UNLOADING_PORT,
java.lang.String FTZ,
java.lang.String VALIDATED_LICENSE,
java.lang.String LICENSE_EXP_DATE,
java.lang.String ECCN,
java.lang.String AUTHORIZED_EMPL_NAME,
java.lang.String AUTHORIZED_EMPL_TITLE,
java.lang.String CONTAINERIZED,
java.lang.String TOTAL_FREIGHT_CHARGE,
java.lang.String CUSTOMER_RESIDENTIAL_FLAG,
java.lang.String SHIPTO_RESIDENTIAL_FLAG,
java.lang.String REJECTION_NOTE,
java.lang.String CUSTOMER_CATEGORY1,
java.lang.String CUSTOMER_CATEGORY2,
java.lang.String CUSTOMER_CATEGORY3,
java.lang.String CUSTOMER_CATEGORY4,
java.lang.String CUSTOMER_CATEGORY5,
java.lang.String CUSTOMER_CATEGORY6,
java.lang.String CUSTOMER_CATEGORY7,
java.lang.String CUSTOMER_CATEGORY8,
java.lang.String CUSTOMER_CATEGORY9,
java.lang.String CUSTOMER_CATEGORY10,
java.lang.String PROCESS_TYPE,
java.lang.String CREATION_PROCESS_STAMP,
java.lang.String CREATION_DATE_TIME_STAMP,
java.lang.String CONSOLIDATION_DOCK_LOC_AREA,
java.lang.String CONSOLIDATION_DOCK_LOC_POS,
java.lang.String IMMEDIATE_NEEDS_NOTE,
java.lang.String ALLOCATE_COMPLETE,
java.lang.String ALTERNATE_EMAIL_ADDRESS,
java.lang.String STOP_SEQUENCE,
java.lang.String CREATE_ORDERS,
java.lang.String STORE_DISTRIBUTION,
java.lang.String SHIPPER_CODE,
java.lang.String USER_DEF9,
java.lang.String USER_DEF10,
java.lang.String USER_DEF11,
java.lang.String USER_DEF12,
java.lang.String USER_DEF13,
java.lang.String USER_DEF14,
java.lang.String USER_DEF15,
java.lang.String USER_DEF16,
java.lang.String USER_DEF17_DATE_TIME,
java.lang.String USER_DEF18_DATE_TIME,
java.lang.String USER_DEF19_DATE_TIME,
java.lang.String USER_DEF20_DATE_TIME
			) {
this.INTERFACE_RECORD_ID = INTERFACE_RECORD_ID;
this.INTERFACE_ACTION_CODE = INTERFACE_ACTION_CODE;
this.INTERFACE_CONDITION = INTERFACE_CONDITION;
this.INTERFACE_ERROR = INTERFACE_ERROR;
this.ACCESSORIAL_CHARGE = ACCESSORIAL_CHARGE;
this.ACTUAL_DELIVERY_DATE_TIME = ACTUAL_DELIVERY_DATE_TIME;
this.ACTUAL_SHIP_DATE_TIME = ACTUAL_SHIP_DATE_TIME;
this.BASE_FREIGHT_CHARGE = BASE_FREIGHT_CHARGE;
this.BOL_NUM_ALPHA = BOL_NUM_ALPHA;
this.CARRIER = CARRIER;
this.CARRIER_SERVICE = CARRIER_SERVICE;
this.CARRIER_GROUP = CARRIER_GROUP;
this.CARRIER_TYPE = CARRIER_TYPE;
this.COMPANY = COMPANY;
this.CONSOLIDATED = CONSOLIDATED;
this.CONSOLIDATION_ALLOWED = CONSOLIDATION_ALLOWED;
this.CONTAINERS_SHIPPED = CONTAINERS_SHIPPED;
this.CUSTOMER = CUSTOMER;
this.CUSTOMER_ADDRESS1 = CUSTOMER_ADDRESS1;
this.CUSTOMER_ADDRESS2 = CUSTOMER_ADDRESS2;
this.CUSTOMER_ADDRESS3 = CUSTOMER_ADDRESS3;
this.CUSTOMER_ATTENTION_TO = CUSTOMER_ATTENTION_TO;
this.CUSTOMER_CITY = CUSTOMER_CITY;
this.CUSTOMER_COUNTRY = CUSTOMER_COUNTRY;
this.CUSTOMER_EMAIL_ADDRESS = CUSTOMER_EMAIL_ADDRESS;
this.CUSTOMER_FAX_NUM = CUSTOMER_FAX_NUM;
this.CUSTOMER_NAME = CUSTOMER_NAME;
this.CUSTOMER_PHONE_NUM = CUSTOMER_PHONE_NUM;
this.CUSTOMER_PO = CUSTOMER_PO;
this.CUSTOMER_POSTAL_CODE = CUSTOMER_POSTAL_CODE;
this.CUSTOMER_STATE = CUSTOMER_STATE;
this.ERP_ORDER = ERP_ORDER;
this.FREIGHT_BILL_TO = FREIGHT_BILL_TO;
this.FREIGHT_BILL_TO_ADDRESS1 = FREIGHT_BILL_TO_ADDRESS1;
this.FREIGHT_BILL_TO_ADDRESS2 = FREIGHT_BILL_TO_ADDRESS2;
this.FREIGHT_BILL_TO_ADDRESS3 = FREIGHT_BILL_TO_ADDRESS3;
this.FREIGHT_BILL_TO_ATTENTION_TO = FREIGHT_BILL_TO_ATTENTION_TO;
this.FREIGHT_BILL_TO_CITY = FREIGHT_BILL_TO_CITY;
this.FREIGHT_BILL_TO_COUNTRY = FREIGHT_BILL_TO_COUNTRY;
this.FREIGHT_BILL_TO_EMAIL_ADDRESS = FREIGHT_BILL_TO_EMAIL_ADDRESS;
this.FREIGHT_BILL_TO_FAX_NUM = FREIGHT_BILL_TO_FAX_NUM;
this.FREIGHT_BILL_TO_NAME = FREIGHT_BILL_TO_NAME;
this.FREIGHT_BILL_TO_PHONE_NUM = FREIGHT_BILL_TO_PHONE_NUM;
this.FREIGHT_BILL_TO_POSTAL_CODE = FREIGHT_BILL_TO_POSTAL_CODE;
this.FREIGHT_BILL_TO_STATE = FREIGHT_BILL_TO_STATE;
this.FREIGHT_DISCOUNT = FREIGHT_DISCOUNT;
this.FREIGHT_TERMS = FREIGHT_TERMS;
this.INTERMEDIATE_ADDRESS1 = INTERMEDIATE_ADDRESS1;
this.INTERMEDIATE_ADDRESS2 = INTERMEDIATE_ADDRESS2;
this.INTERMEDIATE_ADDRESS3 = INTERMEDIATE_ADDRESS3;
this.INTERMEDIATE_ATTENTION_TO = INTERMEDIATE_ATTENTION_TO;
this.INTERMEDIATE_CITY = INTERMEDIATE_CITY;
this.INTERMEDIATE_CONSIGNEE = INTERMEDIATE_CONSIGNEE;
this.INTERMEDIATE_COUNTRY = INTERMEDIATE_COUNTRY;
this.INTERMEDIATE_EMAIL_ADDRESS = INTERMEDIATE_EMAIL_ADDRESS;
this.INTERMEDIATE_FAX_NUM = INTERMEDIATE_FAX_NUM;
this.INTERMEDIATE_NAME = INTERMEDIATE_NAME;
this.INTERMEDIATE_PHONE_NUM = INTERMEDIATE_PHONE_NUM;
this.INTERMEDIATE_POSTAL_CODE = INTERMEDIATE_POSTAL_CODE;
this.INTERMEDIATE_STATE = INTERMEDIATE_STATE;
this.LIABILITY_TERMS = LIABILITY_TERMS;
this.ORDER_DATE = ORDER_DATE;
this.ORDER_TYPE = ORDER_TYPE;
this.PLANNED_DELIVERY_DATE_TIME = PLANNED_DELIVERY_DATE_TIME;
this.PLANNED_SHIP_DATE = PLANNED_SHIP_DATE;
this.PRIORITY = PRIORITY;
this.PRO_NUM_ALPHA = PRO_NUM_ALPHA;
this.QUANTITY_UM = QUANTITY_UM;
this.REQUESTED_DELIVERY_DATE = REQUESTED_DELIVERY_DATE;
this.REQUESTED_DELIVERY_TYPE = REQUESTED_DELIVERY_TYPE;
this.ROUTE = ROUTE;
this.ROUTING_CODE = ROUTING_CODE;
this.SCHEDULED_SHIP_DATE = SCHEDULED_SHIP_DATE;
this.SHIPMENT_ID = SHIPMENT_ID;
this.SHIP_TO_PHONE_NUM = SHIP_TO_PHONE_NUM;
this.SHIP_TO = SHIP_TO;
this.SHIP_TO_ADDRESS1 = SHIP_TO_ADDRESS1;
this.SHIP_TO_ADDRESS2 = SHIP_TO_ADDRESS2;
this.SHIP_TO_ADDRESS3 = SHIP_TO_ADDRESS3;
this.SHIP_TO_ATTENTION_TO = SHIP_TO_ATTENTION_TO;
this.SHIP_TO_CITY = SHIP_TO_CITY;
this.SHIP_TO_COUNTRY = SHIP_TO_COUNTRY;
this.SHIP_TO_EMAIL_ADDRESS = SHIP_TO_EMAIL_ADDRESS;
this.SHIP_TO_FAX_NUM = SHIP_TO_FAX_NUM;
this.SHIP_TO_NAME = SHIP_TO_NAME;
this.SHIP_TO_POSTAL_CODE = SHIP_TO_POSTAL_CODE;
this.SHIP_TO_STATE = SHIP_TO_STATE;
this.SINGLE_ITEM_CARTONS = SINGLE_ITEM_CARTONS;
this.STOP = STOP;
this.VALUE_SHIPPED = VALUE_SHIPPED;
this.VOLUME_SHIPPED = VOLUME_SHIPPED;
this.VOLUME_UM = VOLUME_UM;
this.WAREHOUSE = WAREHOUSE;
this.WEIGHT_SHIPPED = WEIGHT_SHIPPED;
this.WEIGHT_UM = WEIGHT_UM;
this.USER_DEF1 = USER_DEF1;
this.USER_DEF2 = USER_DEF2;
this.USER_DEF3 = USER_DEF3;
this.USER_DEF4 = USER_DEF4;
this.USER_DEF5 = USER_DEF5;
this.USER_DEF6 = USER_DEF6;
this.USER_DEF7 = USER_DEF7;
this.USER_DEF8 = USER_DEF8;
this.USER_STAMP = USER_STAMP;
this.PROCESS_STAMP = PROCESS_STAMP;
this.DATE_TIME_STAMP = DATE_TIME_STAMP;
this.TMP_INTERNAL_ORDER_NUM = TMP_INTERNAL_ORDER_NUM;
this.TMP_INTERNAL_SHIPMENT_NUM = TMP_INTERNAL_SHIPMENT_NUM;
this.EXPORT_TAX_ID = EXPORT_TAX_ID;
this.PARTIES = PARTIES;
this.LOADING_PIER = LOADING_PIER;
this.TRANSPORTATION_MODE = TRANSPORTATION_MODE;
this.EXPORT_PORT = EXPORT_PORT;
this.UNLOADING_PORT = UNLOADING_PORT;
this.FTZ = FTZ;
this.VALIDATED_LICENSE = VALIDATED_LICENSE;
this.LICENSE_EXP_DATE = LICENSE_EXP_DATE;
this.ECCN = ECCN;
this.AUTHORIZED_EMPL_NAME = AUTHORIZED_EMPL_NAME;
this.AUTHORIZED_EMPL_TITLE = AUTHORIZED_EMPL_TITLE;
this.CONTAINERIZED = CONTAINERIZED;
this.TOTAL_FREIGHT_CHARGE = TOTAL_FREIGHT_CHARGE;
this.CUSTOMER_RESIDENTIAL_FLAG = CUSTOMER_RESIDENTIAL_FLAG;
this.SHIPTO_RESIDENTIAL_FLAG = SHIPTO_RESIDENTIAL_FLAG;
this.REJECTION_NOTE = REJECTION_NOTE;
this.CUSTOMER_CATEGORY1 = CUSTOMER_CATEGORY1;
this.CUSTOMER_CATEGORY2 = CUSTOMER_CATEGORY2;
this.CUSTOMER_CATEGORY3 = CUSTOMER_CATEGORY3;
this.CUSTOMER_CATEGORY4 = CUSTOMER_CATEGORY4;
this.CUSTOMER_CATEGORY5 = CUSTOMER_CATEGORY5;
this.CUSTOMER_CATEGORY6 = CUSTOMER_CATEGORY6;
this.CUSTOMER_CATEGORY7 = CUSTOMER_CATEGORY7;
this.CUSTOMER_CATEGORY8 = CUSTOMER_CATEGORY8;
this.CUSTOMER_CATEGORY9 = CUSTOMER_CATEGORY9;
this.CUSTOMER_CATEGORY10 = CUSTOMER_CATEGORY10;
this.PROCESS_TYPE = PROCESS_TYPE;
this.CREATION_PROCESS_STAMP = CREATION_PROCESS_STAMP;
this.CREATION_DATE_TIME_STAMP = CREATION_DATE_TIME_STAMP;
this.CONSOLIDATION_DOCK_LOC_AREA = CONSOLIDATION_DOCK_LOC_AREA;
this.CONSOLIDATION_DOCK_LOC_POS = CONSOLIDATION_DOCK_LOC_POS;
this.IMMEDIATE_NEEDS_NOTE = IMMEDIATE_NEEDS_NOTE;
this.ALLOCATE_COMPLETE = ALLOCATE_COMPLETE;
this.ALTERNATE_EMAIL_ADDRESS = ALTERNATE_EMAIL_ADDRESS;
this.STOP_SEQUENCE = STOP_SEQUENCE;
this.CREATE_ORDERS = CREATE_ORDERS;
this.STORE_DISTRIBUTION = STORE_DISTRIBUTION;
this.SHIPPER_CODE = SHIPPER_CODE;
this.USER_DEF9 = USER_DEF9;
this.USER_DEF10 = USER_DEF10;
this.USER_DEF11 = USER_DEF11;
this.USER_DEF12 = USER_DEF12;
this.USER_DEF13 = USER_DEF13;
this.USER_DEF14 = USER_DEF14;
this.USER_DEF15 = USER_DEF15;
this.USER_DEF16 = USER_DEF16;
this.USER_DEF17_DATE_TIME = USER_DEF17_DATE_TIME;
this.USER_DEF18_DATE_TIME = USER_DEF18_DATE_TIME;
this.USER_DEF19_DATE_TIME = USER_DEF19_DATE_TIME;
this.USER_DEF20_DATE_TIME = USER_DEF20_DATE_TIME;
	}

}